version: '3.8'

services:
  customer:
    build: ./customer
    ports:
      - "3001:3001"
  
  admin:
    build: ./admin
    ports:
      - "3002:3002"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - customer
      - admin

